name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: useversion

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Start auth"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Login successful"
      
      - name: Docker Build
        env:
          NEW_VERSION: ${{ steps.useversion.outputs.version }}
        run: |
          echo "Building image version: ${NEW_VERSION}"
          docker build -t formykez/actions:${NEW_VERSION} graphql-actions
          docker build -t formykez/actions:latest graphql-actions

      - name: Docker Push
        env:
          NEW_VERSION: ${{ steps.useversion.outputs.version }}
        run: |
          echo "Pushing image..."
          docker push formykez/actions:${NEW_VERSION}
          docker push formykez/actions:latest
